// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.2.0.0
//      SpecFlow Generator Version:2.2.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace coIT.MyHeco.Login.Domain.Spec
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class MyHecoNutzerFeature : Xunit.IClassFixture<MyHecoNutzerFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "MyHecoNutzer.feature"
#line hidden
        
        public MyHecoNutzerFeature(MyHecoNutzerFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("de-DE"), "MyHecoNutzer", "Ein MyHecoNutzer ist ein Gast der bereits logindaten besitzt und sich noch nicht " +
                    "eingeloggt hat.", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.ScenarioTearDown();
        }
        
        [Xunit.FactAttribute(DisplayName="My Heco Nutzer loggt sich ein")]
        [Xunit.TraitAttribute("FeatureTitle", "MyHecoNutzer")]
        [Xunit.TraitAttribute("Description", "My Heco Nutzer loggt sich ein")]
        public virtual void MyHecoNutzerLoggtSichEin()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("My Heco Nutzer loggt sich ein", ((string[])(null)));
#line 3
this.ScenarioSetup(scenarioInfo);
#line 4
 testRunner.Given("ein MyHecoBenutzer wurde erkannt.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Angenommen ");
#line 5
 testRunner.When("er das richtige Passwort eingibt", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Wenn ");
#line 6
 testRunner.Then("Ist er ein eingeloggter Benutzer", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dann ");
#line 7
  testRunner.And("darf sich ausloggen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Und ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="My Heco Nutzer loggt sich mit dem falschen password ein")]
        [Xunit.TraitAttribute("FeatureTitle", "MyHecoNutzer")]
        [Xunit.TraitAttribute("Description", "My Heco Nutzer loggt sich mit dem falschen password ein")]
        public virtual void MyHecoNutzerLoggtSichMitDemFalschenPasswordEin()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("My Heco Nutzer loggt sich mit dem falschen password ein", ((string[])(null)));
#line 9
this.ScenarioSetup(scenarioInfo);
#line 10
 testRunner.Given("ein MyHecoBenutzer wurde erkannt.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Angenommen ");
#line 11
 testRunner.When("er das falsche password 1 mal eingibt", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Wenn ");
#line 12
 testRunner.Then("ist er ein MyHecoNutzer", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dann ");
#line 13
  testRunner.And("darf sich mithilfe seines Passwortes einloggen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Und ");
#line 14
  testRunner.And("darf sein Passwort zurücksetzen.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Und ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="My Heco Nutzer loggt sich mit dem falschen password zu oft ein")]
        [Xunit.TraitAttribute("FeatureTitle", "MyHecoNutzer")]
        [Xunit.TraitAttribute("Description", "My Heco Nutzer loggt sich mit dem falschen password zu oft ein")]
        public virtual void MyHecoNutzerLoggtSichMitDemFalschenPasswordZuOftEin()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("My Heco Nutzer loggt sich mit dem falschen password zu oft ein", ((string[])(null)));
#line 16
this.ScenarioSetup(scenarioInfo);
#line 17
 testRunner.Given("ein MyHecoBenutzer wurde erkannt.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Angenommen ");
#line 18
 testRunner.When("er das falsche password 3 mal eingibt", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Wenn ");
#line 19
 testRunner.Then("ist er ein gesperrter Benutzer", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dann ");
#line 20
  testRunner.And("darf nichts", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Und ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                MyHecoNutzerFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                MyHecoNutzerFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
