// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.2.0.0
//      SpecFlow Generator Version:2.2.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace coIT.MyHeco.Login.Domain.Spec
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class NichtAktivierterNutzerFeature : Xunit.IClassFixture<NichtAktivierterNutzerFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "NichtAktivierterNutzer.feature"
#line hidden
        
        public NichtAktivierterNutzerFeature(NichtAktivierterNutzerFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("de-DE"), "NichtAktivierterNutzer", "Ein nicht aktivierter Nutzer hat eine Aktivierung angefragt. Sein Account wurde i" +
                    "n MyHeco erstellt aber die Email wurde noch nicht verifiziert.", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.ScenarioTearDown();
        }
        
        [Xunit.FactAttribute(DisplayName="ein nicht aktivierter Nutzer aktiviert sich")]
        [Xunit.TraitAttribute("FeatureTitle", "NichtAktivierterNutzer")]
        [Xunit.TraitAttribute("Description", "ein nicht aktivierter Nutzer aktiviert sich")]
        public virtual void EinNichtAktivierterNutzerAktiviertSich()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ein nicht aktivierter Nutzer aktiviert sich", ((string[])(null)));
#line 3
this.ScenarioSetup(scenarioInfo);
#line 4
 testRunner.Given("ein nicht aktivierter Nutzer wurde erkannt.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Angenommen ");
#line 5
 testRunner.When("er seinen Account aktiviert und ein Password eingibt.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Wenn ");
#line 6
 testRunner.Then("Ist er ein eingeloggter Nutzer.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dann ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="ein nicht aktivierter Nutzer erscheint und gibt aktivierungscode falsch ein")]
        [Xunit.TraitAttribute("FeatureTitle", "NichtAktivierterNutzer")]
        [Xunit.TraitAttribute("Description", "ein nicht aktivierter Nutzer erscheint und gibt aktivierungscode falsch ein")]
        public virtual void EinNichtAktivierterNutzerErscheintUndGibtAktivierungscodeFalschEin()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ein nicht aktivierter Nutzer erscheint und gibt aktivierungscode falsch ein", ((string[])(null)));
#line 8
this.ScenarioSetup(scenarioInfo);
#line 9
 testRunner.Given("ein nicht aktivierter Nutzer wurde erkannt.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Angenommen ");
#line 10
 testRunner.When("er seinen Account mit dem falschen Code aktiviert und ein Password eingibt.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Wenn ");
#line 11
 testRunner.Then("ist er ein nicht aktiviertem Nutzer.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dann ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                NichtAktivierterNutzerFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                NichtAktivierterNutzerFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
