// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.2.0.0
//      SpecFlow Generator Version:2.2.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace coIT.MyHeco.Login.Domain.Spec
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class WebseitenNutzerFeature : Xunit.IClassFixture<WebseitenNutzerFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "WebseitenNutzer.feature"
#line hidden
        
        public WebseitenNutzerFeature(WebseitenNutzerFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("de-DE"), "WebseitenNutzer", "Ein WebseitenNutzer ist jeder der initial auf die Webseite kommt und noch keine A" +
                    "uthentifizierung gestartet hat. \r\nD.h. die Email von dem Nutzer die als Login ve" +
                    "rwerndet wird ist noch nicht bekannt.", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.ScenarioTearDown();
        }
        
        [Xunit.FactAttribute(DisplayName="Anonymer Nutzer ist unbekannt")]
        [Xunit.TraitAttribute("FeatureTitle", "WebseitenNutzer")]
        [Xunit.TraitAttribute("Description", "Anonymer Nutzer ist unbekannt")]
        public virtual void AnonymerNutzerIstUnbekannt()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Anonymer Nutzer ist unbekannt", ((string[])(null)));
#line 4
this.ScenarioSetup(scenarioInfo);
#line 5
 testRunner.Given("ein nicht angemeldeter Benutzer kommt auf die Webseite.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Angenommen ");
#line 6
 testRunner.When("er eine Email eingibt, die das System nicht kennt", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Wenn ");
#line 7
 testRunner.Then("wird er zu einem unbekannten Nutzer", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dann ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="Anonymer Nutzer ist im Comwork bekannt")]
        [Xunit.TraitAttribute("FeatureTitle", "WebseitenNutzer")]
        [Xunit.TraitAttribute("Description", "Anonymer Nutzer ist im Comwork bekannt")]
        public virtual void AnonymerNutzerIstImComworkBekannt()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Anonymer Nutzer ist im Comwork bekannt", ((string[])(null)));
#line 9
this.ScenarioSetup(scenarioInfo);
#line 10
 testRunner.Given("ein nicht angemeldeter Benutzer kommt auf die Webseite.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Angenommen ");
#line 11
 testRunner.When("er eine Email eingibt, die im Comwork hinterlegt ist", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Wenn ");
#line 12
 testRunner.Then("wird er zu einem ComworkNutzer", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dann ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="Anonymer Nutzer ist im MyHeco bekannt")]
        [Xunit.TraitAttribute("FeatureTitle", "WebseitenNutzer")]
        [Xunit.TraitAttribute("Description", "Anonymer Nutzer ist im MyHeco bekannt")]
        public virtual void AnonymerNutzerIstImMyHecoBekannt()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Anonymer Nutzer ist im MyHeco bekannt", ((string[])(null)));
#line 14
this.ScenarioSetup(scenarioInfo);
#line 15
 testRunner.Given("ein nicht angemeldeter Benutzer kommt auf die Webseite.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Angenommen ");
#line 16
 testRunner.When("er eine Email eingibt, die im MyHeco hinterlegt ist", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Wenn ");
#line 17
 testRunner.Then("ist er ein MyHecoNutzer", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dann ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                WebseitenNutzerFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                WebseitenNutzerFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
